import { Container } from '@chakra-ui/react'
import Head from 'next/head'
import {Header} from './components/header'
import { Navbar } from './components/navbar'

export default function Home() {
  
  return (
    <div >
      <Head>
        <title>Angel SM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Container maxW='1440px' >
      <Header/>
      </Container>
    </div>
  )
}
